config/routes.rb
Saltosaurus::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, controllers: { omniauth_callbacks: 'user/omniauth_callbacks' }
  get "about/index"
  get "projects/index"
  resources :about

  resources :admin

  resources :collections

  resources :anthologies, controller: 'collections', type: 'Anthology', defaults: { type: 'Anthology' }

  resources :novels, controller: 'collections', type: 'Novel', defaults: { type: 'Novel' }

  resources :comments

  resources :projects

  resources :stories

  resources :short_stories, controller: 'stories', type: 'ShortStory', defaults: { type: 'ShortStory' }, path: '/short'

  resources :chapters, controller: 'stories', type: 'Chapter', defaults: { type: 'Chapter' }

  resources :blog_entries, controller: 'stories', type: 'BlogEntry', defaults: { type: 'BlogEntry' }, path: '/blog'

  resources :users

  root 'welcome#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :comments, as: :commentable
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :title, presence: true
  validates :author, presence: true
  validates :completed, inclusion: {in: [true, false]}
  validates :completed_on, presence: true, if: :completed
  validates :type, presence: true

  def latest_story_date
  end

  def stories
  end

  def self.get_archives
    archives = {}
    Collection.all.sort_by(&:latest_story_date).reverse.group_by{|x| x.completed_on.beginning_of_month if x.completed_on}.each do |date, stories|
      archives[date.strftime('%B %Y')] = stories.count if date
    end
    archives
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :set_author, only: [:create, :update]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @archives = {}
    Collection.all.sort_by(&:latest_story_date).reverse.group_by{|x| x.completed_on.beginning_of_month if x.completed_on}.each do |date, stories|
      @archives[date.strftime('%B %Y')] = stories.count if date
    end
    @collections = Collection.page(params[:page]).per(5).where(type: params[:type])
    @type = params[:type]
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    puts @collection.stories
    @stories = Story.page(params[:page]).per(3).where(in? @collection.stories)
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(@params)
    puts @collection.inspect
    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @collection }
      else
        format.html { render action: 'new' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(@params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

  # When author is passed as user_id, find user and replace in params hash
    def set_author
      user = User.find(collection_params[:author])
      @params = {author: user, title: collection_params[:title], completed: collection_params[:completed], type: collection_params[:type]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:title, :author, :completed, :type)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_archives.html.erb
<div class="sidebar-module">
  <h4>Archives</h4>
  <ol class="list-unstyled">
    <% @archives.each do |date, count| %>
        <li><%= link_to date, '#' %> (<%= count %>)</li>
    <% end %>
  </ol>
</div>

app/views/collections/_content.html.erb
<% @collections.each do |collection| %>

    <div class="blog-post">
      <h2 class="blog-post-title"><%= link_to collection.title, collection %></h2>
      <p class="blog-post-meta">Written by <%= link_to collection.author.display_name, collection.author %> <%= collection.completed ? 'and finished '+collection.completed_on.to_s : 'but not yet finished' %>.</p>

      <% @stories = collection.stories %>

      <% for story in @stories.limit(5) do %>
        <h4><%= link_to story.title, story %></h4>
        <p class="blog-post-meta">Written by <%= link_to story.author.display_name, story.author %> on <%= story.published_on.to_date.to_s %>.</p>
      <% end %>
      <% if @stories.count > 5 %>
        <p>Some stories have been hidden. <%= link_to 'See the rest?', collection %></p>
      <% end %>
    </div><!-- /.blog-post -->

<% end %>

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.datetime_select :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/_show.html.erb
<div class="blog-post">
  <% @stories.each do |story| %>
      <h2 class="blog-post-title"><%= link_to story.title, story %></h2>
      <p class="blog-post-meta">Written by <%= link_to story.author.display_name, story.author %> on <%= story.published_on.to_date.to_s %>.</p>
      <%= story.content %>
  <% end %>
  <div id="entry_info"><%= page_entries_info @stories %>.</div>
  <div><%= paginate @stories %></div>
</div><!-- /.blog-post -->

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<script>$('.<%= @type %>').addClass('active')</script>
<div class="container">
  <div class="blog-header">
    <h2 class="blog-title">So Says The Saltosaurus</h2>
  </div>

  <div class="row">
    <div class="col-sm-8 blog-main">

      <%= render 'content' %>

      <div id="entry_info"><%= page_entries_info @collections %>.</div>

      <div><%= paginate @collections %></div>



    </div><!-- /.blog-main -->

    <div class="col-sm-3 col-sm-offset-1 hidden-xs blog-sidebar">

      <%= render 'archives' %>

    </div><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</div><!-- /.container -->

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<div class="container">
  <div class="blog-header">
    <h2 class="blog-title"><%= @collection.title %></h2>
    <p class="blog-post-meta">Written by <%= link_to @collection.author.display_name, @collection.author %> <%= @collection.completed ? 'and finished '+@collection.completed_on.to_s : 'but not yet finished' %>.</p>
  </div>

  <div class="row">

    <div class="col-sm-11 blog-main">

      <div class="blog-post">

        <%= render 'show' %>

      </div><!-- /.blog-post -->

    </div><!-- /.blog-main -->

  </div><!-- /.row -->

</div><!-- /.container -->