config/routes.rb
Saltosaurus::Application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users, controllers: { omniauth_callbacks: 'user/omniauth_callbacks' }
  get "about/index"
  get "projects/index"
  resources :about

  resources :admin

  resources :collections

  resources :anthologies, controller: 'collections', type: 'Anthology', defaults: { type: 'Anthology' }

  resources :novels, controller: 'collections', type: 'Novel', defaults: { type: 'Novel' }

  resources :comments

  resources :projects

  resources :stories

  resources :short_stories, controller: 'stories', type: 'ShortStory', defaults: { type: 'ShortStory' }, path: '/short'

  resources :chapters, controller: 'stories', type: 'Chapter', defaults: { type: 'Chapter' }

  resources :blog_entries, controller: 'stories', type: 'BlogEntry', defaults: { type: 'BlogEntry' }, path: '/blog'

  resources :users

  root 'welcome#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :comments, as: :commentable
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :author, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :published_on, presence: true
  validates :type, presence: true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :set_author, only: [:create, :update]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @archives = {}
    Story.where(type: params[:type]).order('published_on').reverse.group_by{|x| x.published_on.beginning_of_month}.each do |date, stories|
      @archives[date.strftime('%B %Y')] = stories.count
    end
    @stories = Story.page(params[:page]).per(3).where(type: params[:type])
    @type = params[:type]
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(@params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      print @params
      if @story.update(@params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # When author is passed as user_id, find user and replace in params hash
    def set_author
      @params = {author: current_user, title: story_params[:title], content: story_params[:content], published_on: DateTime.now, type: story_params[:type]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :content, :author, :published_on, :type)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_content.html.erb
<% @stories.each do |story| %>

    <div class="blog-post">
      <h2 class="blog-post-title"><%= link_to story.title, story %></h2>
      <p class="blog-post-meta">Written <%= distance_of_time_in_words story.published_on, Time.now %> ago by <%= link_to story.author.display_name, story.author %>.</p>

      <%= story.content.html_safe %>
    </div><!-- /.blog-post -->

<% end %>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.bootsy_area :content, rows: 12, cols: 100 %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.collection_select :type, Story.descendants, :name, :to_s, {include_blank: true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<script>$('.<%= @type %>').addClass('active')</script>
<div class="container">
  <div class="blog-header">
    <h2 class="blog-title">So Says The Saltosaurus</h2>
  </div>

  <div class="row">
    <div class="col-sm-8 blog-main">

      <%= render 'content' %>

      <div id="entry_info"><%= page_entries_info @stories %>.</div>

      <div><%= paginate @stories %></div>



    </div><!-- /.blog-main -->

    <div class="col-sm-3 col-sm-offset-1 hidden-xs blog-sidebar">

      <%= render 'archives' %>

    </div><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</div><!-- /.container -->

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<div class="container">
  <div class="blog-header">
    <h2 class="blog-title"><%= @story.title %></h2>
    <p class="blog-post-meta">Written <%= distance_of_time_in_words @story.published_on, Time.now %> ago by <%= link_to @story.author.display_name, @story.author %>.</p>
  </div>

  <div class="row">

    <div class="col-sm-11 blog-main">

      <div class="blog-post">

        <%=raw @story.content %>

      </div><!-- /.blog-post -->

    </div><!-- /.blog-main -->

  </div><!-- /.row -->

</div><!-- /.container -->